// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmXpCxb2-BHnZmEPXGeWA3okT_i1ItSI',
    appId: '1:33103850184:web:5de451f9bd3b9f85c9d3fd',
    messagingSenderId: '33103850184',
    projectId: 'graduation2-fb874',
    authDomain: 'graduation2-fb874.firebaseapp.com',
    databaseURL: 'https://graduation2-fb874-default-rtdb.firebaseio.com',
    storageBucket: 'graduation2-fb874.appspot.com',
    measurementId: 'G-J126KFNYPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBhhKmFD_CYvZWcZuTwn8mlbZJI3uM2Y',
    appId: '1:33103850184:android:9c02bab765b2dc9dc9d3fd',
    messagingSenderId: '33103850184',
    projectId: 'graduation2-fb874',
    databaseURL: 'https://graduation2-fb874-default-rtdb.firebaseio.com',
    storageBucket: 'graduation2-fb874.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr78L9Q4yQ1SdVwCIFnoiC8fRfqqUjEMI',
    appId: '1:33103850184:ios:0b2c56b56775bc6fc9d3fd',
    messagingSenderId: '33103850184',
    projectId: 'graduation2-fb874',
    databaseURL: 'https://graduation2-fb874-default-rtdb.firebaseio.com',
    storageBucket: 'graduation2-fb874.appspot.com',
    iosBundleId: 'com.example.comfyview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr78L9Q4yQ1SdVwCIFnoiC8fRfqqUjEMI',
    appId: '1:33103850184:ios:5cf2b4c7e7061a03c9d3fd',
    messagingSenderId: '33103850184',
    projectId: 'graduation2-fb874',
    databaseURL: 'https://graduation2-fb874-default-rtdb.firebaseio.com',
    storageBucket: 'graduation2-fb874.appspot.com',
    iosBundleId: 'com.example.comfyview.RunnerTests',
  );
}
